import crypto from "crypto";

/* Meta Conversions API — server-side mirror of the browser pixel. It recovers
   conversions the browser pixel loses to iOS/ad-blockers/privacy, which improves
   both measurement and Meta's ad optimization.

   No-op unless BOTH the pixel id (NEXT_PUBLIC_META_PIXEL_ID) and a server access
   token (META_CAPI_TOKEN) are set — so it's safe to call unconditionally. The
   token is generated by the user in Events Manager → Data Sources → your pixel →
   Settings → Conversions API → "Generate access token" and pasted into Render env
   (a secret; handled like the Stripe keys). Never throws.

   Event Match Quality (EMQ): we send as many customer-match signals as we have —
   hashed email + first name, plus the Meta browser cookies (_fbp / _fbc), client
   IP and user-agent. fbp/fbc/IP/UA are captured in the browser at checkout time
   and threaded through Stripe session metadata to this server call.

   Dedupe: pass the SAME eventId used by the browser pixel (the order number) so
   Meta merges the browser + server Purchase into one event, never double-counting. */

const PIXEL_ID = process.env.NEXT_PUBLIC_META_PIXEL_ID;
const CAPI_TOKEN = process.env.META_CAPI_TOKEN;
const TEST_EVENT_CODE = process.env.META_CAPI_TEST_EVENT_CODE; // optional — only for Events Manager "Test events"
const GRAPH_VERSION = "v21.0";

function hash(value: string): string {
  return crypto.createHash("sha256").update(value.trim().toLowerCase()).digest("hex");
}

export type MetaCapiEvent = {
  eventName: "Purchase" | "InitiateCheckout" | "Lead" | "PageView";
  eventId: string; // dedupe key — must match the browser pixel's eventID
  email?: string;
  name?: string; // full name; the first token is sent as a hashed first name (fn)
  value?: number;
  currency?: string;
  sourceUrl?: string;
  clientIp?: string;
  userAgent?: string;
  fbp?: string; // Meta browser cookie _fbp — sent un-hashed
  fbc?: string; // Meta click cookie _fbc — sent un-hashed
};

export async function sendMetaCapiEvent(e: MetaCapiEvent): Promise<void> {
  if (!PIXEL_ID || !CAPI_TOKEN || CAPI_TOKEN.includes("REPLACE_ME")) return;
  try {
    const user_data: Record<string, unknown> = {};
    if (e.email) user_data.em = [hash(e.email)];
    const firstName = e.name?.trim().split(/\s+/)[0];
    if (firstName) user_data.fn = [hash(firstName)];
    if (e.clientIp) user_data.client_ip_address = e.clientIp;
    if (e.userAgent) user_data.client_user_agent = e.userAgent;
    if (e.fbp) user_data.fbp = e.fbp; // fbp/fbc are NOT hashed
    if (e.fbc) user_data.fbc = e.fbc;

    const payload = {
      data: [
        {
          event_name: e.eventName,
          event_time: Math.floor(Date.now() / 1000),
          event_id: e.eventId,
          action_source: "website",
          ...(e.sourceUrl ? { event_source_url: e.sourceUrl } : {}),
          user_data,
          ...(e.value != null
            ? { custom_data: { value: e.value, currency: e.currency ?? "USD" } }
            : {}),
        },
      ],
      ...(TEST_EVENT_CODE ? { test_event_code: TEST_EVENT_CODE } : {}),
    };

    const res = await fetch(
      `https://graph.facebook.com/${GRAPH_VERSION}/${PIXEL_ID}/events?access_token=${encodeURIComponent(CAPI_TOKEN)}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      }
    );

    /* Surface rejections. This call used to discard the response entirely, which
       meant an expired token or a malformed payload was indistinguishable from
       success — conversions would just quietly stop arriving. Log loudly instead;
       CAPI is load-bearing for ad optimisation now.

       NEVER log the request URL: the access token rides in its query string. */
    if (!res.ok) {
      const body = await res.text().catch(() => "<unreadable>");
      console.error(
        `[meta-capi] ${e.eventName} ${e.eventId} rejected: HTTP ${res.status} ${body.slice(0, 500)}`
      );
    } else {
      console.log(`[meta-capi] ${e.eventName} ${e.eventId} accepted`);
    }
  } catch (err) {
    // Message only — a thrown fetch error can carry the tokenised URL in `cause`.
    console.error(
      `[meta-capi] ${e.eventName} ${e.eventId} failed to send: ${
        err instanceof Error ? err.message : String(err)
      }`
    );
    // Conversions API must never affect the request that triggered it.
  }
}
