import crypto from "crypto";

/* Meta Conversions API — server-side mirror of the browser pixel. It recovers
   conversions the browser pixel loses to iOS/ad-blockers/privacy, which improves
   both measurement and Meta's optimization.

   No-op unless BOTH the pixel id (NEXT_PUBLIC_META_PIXEL_ID) and a server access
   token (META_CAPI_TOKEN) are set — so it's safe to call unconditionally. The
   token is generated by the user in Events Manager → Settings → Conversions API
   and pasted into Render env (a secret; handled like the Stripe keys).

   Dedupe: pass the SAME eventId used by the browser pixel (the order number) so
   Meta merges the two Purchase events into one. Never throws. */

const PIXEL_ID = process.env.NEXT_PUBLIC_META_PIXEL_ID;
const CAPI_TOKEN = process.env.META_CAPI_TOKEN;
const GRAPH_VERSION = "v21.0";

function hash(value: string): string {
  return crypto.createHash("sha256").update(value.trim().toLowerCase()).digest("hex");
}

export type MetaCapiEvent = {
  eventName: "Purchase" | "InitiateCheckout" | "Lead" | "PageView";
  eventId: string; // dedupe key — must match the browser pixel's eventID
  email?: string;
  value?: number;
  currency?: string;
  sourceUrl?: string;
  clientIp?: string;
  userAgent?: string;
};

export async function sendMetaCapiEvent(e: MetaCapiEvent): Promise<void> {
  if (!PIXEL_ID || !CAPI_TOKEN || CAPI_TOKEN.includes("REPLACE_ME")) return;
  try {
    const user_data: Record<string, unknown> = {};
    if (e.email) user_data.em = [hash(e.email)];
    if (e.clientIp) user_data.client_ip_address = e.clientIp;
    if (e.userAgent) user_data.client_user_agent = e.userAgent;

    const payload = {
      data: [
        {
          event_name: e.eventName,
          event_time: Math.floor(Date.now() / 1000),
          event_id: e.eventId,
          action_source: "website",
          ...(e.sourceUrl ? { event_source_url: e.sourceUrl } : {}),
          user_data,
          ...(e.value != null
            ? { custom_data: { value: e.value, currency: e.currency ?? "USD" } }
            : {}),
        },
      ],
    };

    await fetch(
      `https://graph.facebook.com/${GRAPH_VERSION}/${PIXEL_ID}/events?access_token=${encodeURIComponent(CAPI_TOKEN)}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      }
    );
  } catch {
    // Conversions API must never affect the request that triggered it.
  }
}
